--what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customers_cleanedd
group by gender

--which customer used a discount but still they spent more than average amount?
select purchase_amount,customer_id
from customers_cleanedd
where 'discount_applied'='Yes' and purchase_amount>=(select avg(purchase_amount) as avrg from customers_cleanedd)

--which are the top 5 products with highest average review rating?
select item_purchased,round(avg(review_rating)) as 'average_product_rating'
from customers_cleanedd
group by item_purchased
order by avg(review_rating) DESC
limit  5

--companre average purchase amounts between standard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount)) AS avg_purchase_amount
FROM customers_cleanedd
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
       count(customer_id) as total_customers,
       round(avg(purchase_amount), 2) as avg_spend,
       round(sum(purchase_amount), 2) as total_revenue
from customers_cleanedd
group by subscription_status
order by total_revenue desc, avg_spend desc;
